"""Turns the rbx-dom reflection database (msgpack) into a Luau module.

Upstream Argon built its plugin with Argon, which converts `.msgpack` files
into ModuleScripts on the fly. Aragon builds the plugin with Rojo, which
ignores `.msgpack`, so we pre-generate the exact same module source here
(port of `msgpack_to_lua` in src/middleware/msgpack.rs).

Usage: python plugin/scripts/gen_database.py
"""

import math
import os

import msgpack

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "database.msgpack")
TARGET = os.path.join(HERE, "..", "src", "Lib", "Dom", "database.luau")


def escape(text):
    return (
        text.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
        .replace('"', '\\"')
    )


def number(value):
    if isinstance(value, float):
        if math.isinf(value):
            return "math.huge" if value > 0 else "-math.huge"
        if math.isnan(value):
            return "0/0"
        return repr(value)
    return str(value)


def to_lua(value, out):
    if value is None:
        out.append("nil")
    elif isinstance(value, bool):
        out.append("true" if value else "false")
    elif isinstance(value, (int, float)):
        out.append(number(value))
    elif isinstance(value, str):
        out.append('"' + escape(value) + '"')
    elif isinstance(value, (bytes, bytearray)):
        out.append(value.decode("utf-8", "replace"))
    elif isinstance(value, (list, tuple)):
        out.append("{")
        for item in value:
            to_lua(item, out)
            out.append(",")
        out.append("}")
    elif isinstance(value, dict):
        out.append("{")
        for key, item in value.items():
            out.append("[")
            to_lua(key, out)
            out.append("] = ")
            to_lua(item, out)
            out.append(",")
        out.append("}")
    else:
        raise TypeError(f"Unsupported msgpack value: {type(value)}")


def main():
    with open(SOURCE, "rb") as file:
        data = msgpack.unpackb(file.read(), raw=False, strict_map_key=False)

    out = ["-- Generated by plugin/scripts/gen_database.py from database.msgpack, do not edit\n", "return "]
    to_lua(data, out)
    out.append("\n")

    with open(TARGET, "w", encoding="utf-8", newline="\n") as file:
        file.write("".join(out))

    print(f"Wrote {os.path.relpath(TARGET)} ({os.path.getsize(TARGET) // 1024} KiB)")


if __name__ == "__main__":
    main()
