#!/bin/bash
# Installs the plugin's Wally packages and their type exports

wally install &&
rojo sourcemap default.project.json --output sourcemap.json &&
wally-package-types --sourcemap sourcemap.json Packages
